### ISSUE TITLE
Lỗi khi dùng với php 8.2

### ISSUE THREAD

**Issue by JeoriTr** [nguyenanhung/codeigniter-framework#51]
A PHP Error was encountered
Severity: 8192

Message: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated

Filename: libraries/Pagination.php

Line Number: 517

Lỗi này khắc phục sao vậy anh?

**Comment by nguyenanhung** [comment]
Hi @JeoriTr , sorry vì hôm nay mới check thấy bug này

Mình đã fix, releases bản fix này tại version 3.2.0.24 nhé

Bạn có thể composer update để nhận bản vá mới.

**Comment by nguyenanhung** [comment]
k9
