### ISSUE TITLE
Một số lỗi khi chạy trên php8.2

### ISSUE THREAD

**Issue by JeoriTr** [nguyenanhung/codeigniter-framework#63]
<h4>A PHP Error was encountered</h4>

<p>Severity: 8192</p>
<p>Message:  strtolower(): Passing null to parameter #1 ($string) of type string is deprecated</p>
<p>Filename: core/Input.php</p>
<p>Line Number: 911</p>

<p>Severity: 8192</p>
<p>Message:  strtoupper(): Passing null to parameter #1 ($string) of type string is deprecated</p>
<p>Filename: core/Security.php</p>
<p>Line Number: 224</p>

**Comment by nguyenanhung** [comment]
Thank @JeoriTr report, 1 bản vá ([v3.2.0.34](https://github.com/nguyenanhung/codeigniter-framework/releases/tag/v3.2.0.34)) đã được release để xử lý lỗi này. 

Nếu tìm thấy bất cứ lỗi nào, hãy tạo thêm issues nhé
